### ISSUE TITLE
Database schema

### ISSUE THREAD

**Issue by skpassegna** [devilandcode/Telegram-bot-Garant#1]
Hello,
I wanted to test your code, but the database schema is not available. 
The README is incomplete too.

**Comment by devilandcode** [comment]
> Hello,
> I wanted to test your code, but the database schema is not available.
> The README is incomplete too.

I just decided to do a complete refactoring of my code, I think you'll be able to test it out in a couple of days. I will also post a database dump and finish the Read.me file

**Comment by devilandcode** [comment]
> Hello,
> I wanted to test your code, but the database schema is not available.
> The README is incomplete too.

U can check repository
